spring.application.name=app

# 1. Configuracion de la Base de Datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/optify_local}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:gonza28294}
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuracion de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Seguridad y API
optify.api.key=${OPTIFY_API_KEY:clave_secreta_optify}
logging.level.org.springframework.security=DEBUG

# 4. Optimizacion de Batch
spring.jpa.properties.hibernate.jdbc.batch_size=200
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true

# 5. Frontend URL
optify.frontend.url=${FRONTEND_URL:http://localhost:5173}
